@host = https://localhost:7148

POST  {{host}}/auth/register HTTP/1.1
content-type: application/json

    {
        "FirstName" : "Imane",
        "LastName" : "Cherraj",
        "Email" : "cherrajimane@icloud.com",
        "Password" : "helloworld"
    }
